# Generated by Django 3.2.4 on 2021-07-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30, null=True)),
                ('TypeZone', models.CharField(max_length=30, null=True)),
                ('GPSPoints', models.TextField()),
                ('ColorZone', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
