# Generated by Django 3.2.4 on 2021-07-12 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeZone', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='zone',
            name='TypeZone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.typeofzone'),
        ),
    ]
