# Generated by Django 3.2.4 on 2021-10-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_auto_20210712_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofzone',
            name='ColorZone',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='ColorZone',
            field=models.CharField(max_length=7),
        ),
    ]
