# Generated by Django 3.2.4 on 2021-10-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_auto_20211005_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofzone',
            name='CanYouParkingOnThisArea',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='typeofzone',
            name='CanYouScooterOnThisArea',
            field=models.BooleanField(null=True),
        ),
    ]
