# Generated by Django 3.2.4 on 2021-12-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_auto_20211005_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofzone',
            name='MaxSpeed',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
