# Generated by Django 3.2.4 on 2021-12-13 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0007_typeofzone_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusesOfPromoCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusOfPromoCode', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypesOfPromoCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeOfPromoCode', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfPromoCode', models.CharField(max_length=30, null=True)),
                ('Limit', models.IntegerField(max_length=3, null=True)),
                ('Sum', models.DecimalField(decimal_places=2, max_digits=7)),
                ('StartOfActive', models.DateTimeField()),
                ('EndOfActive', models.DateTimeField()),
                ('DateOfCreation', models.DateField(auto_now_add=True)),
                ('StatusOfPromoCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.statusesofpromocodes')),
                ('TypeOfPromoCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.typesofpromocodes')),
            ],
        ),
    ]
